apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: backend-prod-secret
  namespace: api
spec:
  encryptedData:
    SOME_KEY: AgB9ZQ== # base64 encoded value
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: backend-prod-secret
      namespace: api
    type: Opaque
